import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import rolesRouter from "./roles";
import dashboardRouter from "./dashboard";
import storeSettingsRouter from "./store-settings";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import ingredientsRouter from "./ingredients";
import stockMovementsRouter from "./stock-movements";
import recipesRouter from "./recipes";
import reportsRouter from "./reports";
import shiftsRouter from "./shifts";
import tablesRouter from "./tables";
import transactionsRouter from "./transactions";
import qrisSettingsRouter from "./qris-settings";
import printerSettingsRouter from "./printer-settings";
import printLogsRouter from "./print-logs";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(dashboardRouter);
router.use(storeSettingsRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(ingredientsRouter);
router.use(stockMovementsRouter);
router.use(recipesRouter);
router.use(reportsRouter);
router.use(shiftsRouter);
router.use(tablesRouter);
router.use(transactionsRouter);
router.use(qrisSettingsRouter);
router.use(printerSettingsRouter);
router.use(printLogsRouter);

export default router;
